### ISSUE TITLE
missing required architecture x86_64 in file 

### ISSUE THREAD

**Issue by CodeEagle** [Krivoblotsky/KSAudioPlayer#1]
Hi Krivoblotsky,
   Could you add support for 64bit?

**Comment by Krivoblotsky** [comment]
Hi there. Finally, BASS library has been updated to include x86_64 architecture. I'll update audio player shortly.

**Comment by Krivoblotsky** [comment]
Hi. This repo was move to another account:
https://github.com/Alterplay/APAudioPlayer

I've submitted the update today and added x86_64 support to it. Thanks for contributing.
