### ISSUE TITLE
"- (BOOL)playItemWithURL:(NSURL *)url Position:(NSTimeInterval)position" block the app

### ISSUE THREAD

**Issue by flyling** [Krivoblotsky/KSAudioPlayer#2]
sorry that my english is poor.my app have some unknow musics.they can't be played.

```
BASS_ChannelStop(_channel);

//Free memory
BASS_StreamFree(_channel);



NSString* filePath = [url absoluteString];
if([filePath hasPrefix:@"ipod-library:"])
{
    _channel= BASS_StreamCreateURL([[url absoluteString] UTF8String], 0, 0, 0, 0);
}
else
{
    _channel = BASS_StreamCreateFile(FALSE, [[url path] cStringUsingEncoding:NSUTF8StringEncoding], 0, 0, 0);
}

if(_channel == 0)
{
    NSLog(@"can't play music %@",filePath);
}
```

_channel = 0.the user interface was  blocked for a few seconds .what can i do.help me .when i select one music .it plays and i'll update the interface.

**Comment by Krivoblotsky** [comment]
Do you experience issues when playing tracks from iTunes? ([filePath hasPrefix:@"ipod-library:"] branch)

**Comment by flyling** [comment]
No.i received music from other android device .not from iTunes. it is transmitted via HTTP

**Comment by Krivoblotsky** [comment]
Do you mean you are trying to stream music via HTTP?

**Comment by flyling** [comment]
oh.no.I don’t mean it like that .if the music have wrong format.i want to know why it blocks the main interface.

**Comment by flyling** [comment]
I have solved the problem. i found the length of the music was 00:00.I suspect this is a minor code error issue .  thanks all the same
